# Fabric Admin MCP Server Docker Compose
version: '3.8'
services:
  fabric-admin-mcp:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
    restart: unless-stopped
